webapp:
  replicaCount: 2
  image:
    repository: coodiallen/my-app 
    tag: latest
    pullPolicy: Always

postgres:
  user: devops_user
  password: SuperSecurePassword123
  db: pet_db

ingress:
  host: localhost
